### ISSUE TITLE
Example of use in a GitHub Action?

### ISSUE THREAD

**Issue by agasparovic** [DeveloperC286/is_affected#24]
Hi there,

Do you happen to have an example of how to use this tool in a GitHub Action, similar to the example for GitLab shown here: https://crates.io/crates/is_affected#cicd-examples

Thanks!

**Comment by DeveloperC286** [comment]
I will update the documentation now I am using GitHub.

If you want to run a workflow depending on if a path was affected GitHub Actions has this inbuilt functionality.

https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore

But that functionality is for an entire workflow not for select steps in a workflow, so I will produce an example for you now for that case now.

**Comment by DeveloperC286** [comment]
@agasparovic 

https://github.com/DeveloperC286/is_affected/tree/main/is_affected#cicd-examples

Let me know what you think of the example 👍

**Comment by agasparovic** [comment]
That's perfect - thanks so much!
